/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTenderUploadRouteImport } from './routes/app.tender-upload'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppExplainabilityRouteImport } from './routes/app.explainability'
import { Route as AppEvaluationRouteImport } from './routes/app.evaluation'
import { Route as AppBidderUploadRouteImport } from './routes/app.bidder-upload'
import { Route as AppAuditRouteImport } from './routes/app.audit'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTenderUploadRoute = AppTenderUploadRouteImport.update({
  id: '/tender-upload',
  path: '/tender-upload',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppExplainabilityRoute = AppExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluationRoute = AppEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => AppRoute,
} as any)
const AppBidderUploadRoute = AppBidderUploadRouteImport.update({
  id: '/bidder-upload',
  path: '/bidder-upload',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/audit': typeof AppAuditRoute
  '/app/bidder-upload': typeof AppBidderUploadRoute
  '/app/evaluation': typeof AppEvaluationRoute
  '/app/explainability': typeof AppExplainabilityRoute
  '/app/risk': typeof AppRiskRoute
  '/app/tender-upload': typeof AppTenderUploadRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bidder-upload': typeof AppBidderUploadRoute
  '/app/evaluation': typeof AppEvaluationRoute
  '/app/explainability': typeof AppExplainabilityRoute
  '/app/risk': typeof AppRiskRoute
  '/app/tender-upload': typeof AppTenderUploadRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/audit': typeof AppAuditRoute
  '/app/bidder-upload': typeof AppBidderUploadRoute
  '/app/evaluation': typeof AppEvaluationRoute
  '/app/explainability': typeof AppExplainabilityRoute
  '/app/risk': typeof AppRiskRoute
  '/app/tender-upload': typeof AppTenderUploadRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/audit'
    | '/app/bidder-upload'
    | '/app/evaluation'
    | '/app/explainability'
    | '/app/risk'
    | '/app/tender-upload'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/audit'
    | '/app/bidder-upload'
    | '/app/evaluation'
    | '/app/explainability'
    | '/app/risk'
    | '/app/tender-upload'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/audit'
    | '/app/bidder-upload'
    | '/app/evaluation'
    | '/app/explainability'
    | '/app/risk'
    | '/app/tender-upload'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tender-upload': {
      id: '/app/tender-upload'
      path: '/tender-upload'
      fullPath: '/app/tender-upload'
      preLoaderRoute: typeof AppTenderUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explainability': {
      id: '/app/explainability'
      path: '/explainability'
      fullPath: '/app/explainability'
      preLoaderRoute: typeof AppExplainabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evaluation': {
      id: '/app/evaluation'
      path: '/evaluation'
      fullPath: '/app/evaluation'
      preLoaderRoute: typeof AppEvaluationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bidder-upload': {
      id: '/app/bidder-upload'
      path: '/bidder-upload'
      fullPath: '/app/bidder-upload'
      preLoaderRoute: typeof AppBidderUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppBidderUploadRoute: typeof AppBidderUploadRoute
  AppEvaluationRoute: typeof AppEvaluationRoute
  AppExplainabilityRoute: typeof AppExplainabilityRoute
  AppRiskRoute: typeof AppRiskRoute
  AppTenderUploadRoute: typeof AppTenderUploadRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppBidderUploadRoute: AppBidderUploadRoute,
  AppEvaluationRoute: AppEvaluationRoute,
  AppExplainabilityRoute: AppExplainabilityRoute,
  AppRiskRoute: AppRiskRoute,
  AppTenderUploadRoute: AppTenderUploadRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
